name: AWS ECR
author: Lee Sun-Hyoup <kciter@naver.com>, Pablo Castillo <pablo@castillo.is>
branding:
  icon: upload-cloud
  color: orange
description: Create a ECR repository.
inputs:
  access_key_id:
    description: The AWS access key id
    required: true
  secret_access_key:
    description: The AWS secret access key
    required: true
  account_id:
    description: AWS Account ID
    required: true
  registry_ids:
    description: A comma-delimited list of AWS account IDs that are associated with the ECR registries. If you do not specify a registry, the default ECR registry is assumed
    required: true
    default: ''
  assume_role:
    description: A role to assume under the account_id account.
    required: false
    default: ''
  repo:
    description: Name of your ECR repository
    required: true
  region:
    description: The AWS region
    required: true
  create_repo:
    description: Set this to true to create the repository if it does not already exist
    default: false
  set_repo_policy:
    description: Set this to true to set a policy on the repository
    default: false
  repo_policy_file:
    description: Set this to repository policy statement json file. only used if the set_repo_policy is set to true
    default: repo-policy.json
runs:
  using: docker
  image: Dockerfile
